export enum En {
    Greeting= 'Hi! This bot will help you to find needed information in SIMBAD database. Just press the button below and follow the instructions',
    IdSearch = 'Search by identifier',
    IdSearchStart = 'Enter the object identifier, e.g. TRAPPIST-1',
    IdSearchStarted = 'Searching by identifier %identifier%...',
    'Coordinates(ICRS,ep=J2000,eq=2000)' = 'Coordinates(ICRS,ep=J2000,eq=2000)',
    'Coordinates(FK4,ep=B1950,eq=1950)' = 'Coordinates(FK4,ep=B1950,eq=1950)',
    'Coordinates(Gal,ep=J2000,eq=2000)' = 'Coordinates(Gal,ep=J2000,eq=2000)',
    'hierarchy counts' = 'hierarchy counts',
    'Proper motions' = 'Proper motions',
    'Parallax' = 'Parallax',
    'Radial Velocity' = 'Radial Velocity',
    'Redshift' = 'Redshift',
    'cz' = 'cz',
    'Flux B' = 'Flux B',
    'Flux V' = 'Flux visible',
    'Flux G' = 'Flux G',
    'Flux J' = 'Flux J',
    'Flux H' = 'Flux H',
    'Flux K' = 'Flux K',
    'Spectral type' = 'Spectral type',
    'Identifiers' = 'Identifiers'
}
